version: 2
updates:
  # NPM dependencies for root package
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tari-project/javascript-sdk-maintainers"
    assignees:
      - "tari-project/javascript-sdk-maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: "increase"
    groups:
      production-dependencies:
        patterns:
          - "@tari-project/*"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "typescript"
          - "jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"

  # NPM dependencies for core package
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    reviewers:
      - "tari-project/javascript-sdk-maintainers"
    commit-message:
      prefix: "deps(core)"
      include: "scope"

  # NPM dependencies for wallet package
  - package-ecosystem: "npm"
    directory: "/packages/wallet"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tari-project/javascript-sdk-maintainers"
    commit-message:
      prefix: "deps(wallet)"
      include: "scope"

  # NPM dependencies for build package
  - package-ecosystem: "npm"
    directory: "/packages/build"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
    open-pull-requests-limit: 5
    reviewers:
      - "tari-project/javascript-sdk-maintainers"
    commit-message:
      prefix: "deps(build)"
      include: "scope"

  # Rust dependencies (for future native package)
  - package-ecosystem: "cargo"
    directory: "/native"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tari-project/javascript-sdk-maintainers"
    commit-message:
      prefix: "deps(native)"
      include: "scope"
    groups:
      tari-dependencies:
        patterns:
          - "minotari_*"
          - "tari_*"
        update-types:
          - "minor"
          - "patch"
      napi-dependencies:
        patterns:
          - "napi*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "tari-project/javascript-sdk-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
