[package]
name = "tari-core-native"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "index"

[dependencies]
neon = { version = "0.10", default-features = false, features = ["napi-6"] }
once_cell = "1.19"
libc = "0.2"

# Note: In a real implementation, you would add:
# tari_wallet_ffi = { path = "path/to/tari/base_layer/wallet_ffi" }
# For now, we'll mock the FFI functions

[build-dependencies]
neon-build = "0.10"
