[package]
name = "tari-core-native"
version = "0.1.0"
edition = "2021"
authors = ["Tari Development Team"]
license = "BSD-3-Clause"

[lib]
name = "tari_core_native"
crate-type = ["cdylib"]

[dependencies]
neon = { version = "0.10", default-features = false, features = ["napi-6"] }
once_cell = "1.19"
libc = "0.2"
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
# Temporarily comment out Tari dependencies until we can resolve version compatibility
# tari_common = { git = "https://github.com/tari-project/tari.git", branch = "development" }
# tari_core = { git = "https://github.com/tari-project/tari.git", branch = "development" }
# tari_wallet = { git = "https://github.com/tari-project/tari.git", branch = "development" }
# tari_crypto = { git = "https://github.com/tari-project/tari.git", branch = "development" }

[build-dependencies]
neon-build = "0.10"

[profile.release]
opt-level = 3
lto = true
strip = false

# Platform-specific dependencies
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }
