[package]
name = "tari-core-native"
version = "0.1.0"
edition = "2021"
authors = ["Tari Development Team"]
license = "BSD-3-Clause"

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = { version = "1.0", features = ["napi-6"] }
once_cell = "1.19"
libc = "0.2"
rand = "0.8"  # Added for mock data

[dependencies.neon]
version = "1.0"
default-features = false
features = ["napi-6", "promise-api", "task-api"]

[build-dependencies]
neon-build = "1.0"

[profile.release]
opt-level = 3
lto = true
strip = true

# Platform-specific dependencies
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"

[target.'cfg(target_os = "linux")'.dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }
